### ISSUE TITLE
proof this

### ISSUE THREAD

**Issue by brando90** [brando90/cs522_project#2]
Exercise: 3 stars (bevalR)
Write a relation bevalR in the same style as aevalR, and prove that it is equivalent to beval.
Inductive bevalR: bexp → bool → Prop :=
(* FILL IN HERE *)
.
Lemma beval_iff_bevalR : ∀ b bv,
  bevalR b bv ↔ beval b = bv.
Proof.
  (* FILL IN HERE *) Admitted.
☐
End AExp.

https://softwarefoundations.cis.upenn.edu/lf-current/Imp.html

**Comment by brando90** [comment]
@umenthum is this done?

**Comment by umenthum** [comment]
Yes.
